CREATE TABLE USER (
  ID       INT PRIMARY KEY AUTO_INCREMENT,
  FIRSTNAME VARCHAR(255),
  LASTNAME  VARCHAR(255),
  USERNAME  VARCHAR(255),
  EMAIL     VARCHAR(255),
  PASSWORD  VARCHAR(255),
  ROLE VARCHAR(50),
  BALANCE   INT
);

CREATE TABLE TYPE (
  ID   INT PRIMARY KEY AUTO_INCREMENT,
  TYPE VARCHAR(255),
  ACTIVE BOOLEAN
);

CREATE TABLE SIZE (
  ID   INT PRIMARY KEY AUTO_INCREMENT,
  SIZE INT,
  NAME VARCHAR(255),
  ACTIVE BOOLEAN
);

CREATE TABLE FOOD (
  ID         INT PRIMARY KEY AUTO_INCREMENT,
  TYPE_ID    INT,
  NAME_RU VARCHAR(255),
  NAME_EN VARCHAR(255),
  COMPOS_RU   VARCHAR(255),
  COMPOS_EN   VARCHAR(255),
  PRICE      INT,
  IMG        VARCHAR(255),
  ACTIVE BOOLEAN
);

ALTER TABLE FOOD
  ADD FOREIGN KEY (TYPE_ID) REFERENCES TYPE (ID);



CREATE TABLE CLIENT_ORDER (
  ID      INT PRIMARY KEY AUTO_INCREMENT,
  USER_ID INT,
  SUM     INT,
  ADDRESS VARCHAR(255),
  PHONE VARCHAR(255),
  STATUS VARCHAR(50)
);

CREATE TABLE ORDER_DETAILS (
  ID       INT PRIMARY KEY AUTO_INCREMENT,
  ORDER_ID INT,
  FOOD_ID  INT,
  FOOD_NAME_RU VARCHAR(255),
  FOOD_NAME_EN VARCHAR(255),
  TYPE_ID  INT,
  TYPE_NAME VARCHAR(255),
  SIZE_NAME VARCHAR(255),
  QUANTITY INT,
  PRICE INT

);

ALTER TABLE CLIENT_ORDER
  ADD FOREIGN KEY (USER_ID) REFERENCES USER (ID);

ALTER TABLE ORDER_DETAILS
  ADD FOREIGN KEY (ORDER_ID) REFERENCES CLIENT_ORDER(ID);
ALTER TABLE ORDER_DETAILS
  ADD FOREIGN KEY (FOOD_ID) REFERENCES FOOD(ID);
ALTER TABLE ORDER_DETAILS
  ADD FOREIGN KEY (TYPE_ID) REFERENCES TYPE (ID);
ALTER TABLE ORDER_DETAILS
  ADD FOREIGN KEY (TYPE_NAME) REFERENCES TYPE (TYPE);
ALTER TABLE ORDER_DETAILS
  ADD FOREIGN KEY (SIZE_NAME) REFERENCES SIZE (NAME) ;
ALTER TABLE ORDER_DETAILS
  ADD FOREIGN KEY (FOOD_NAME_RU) REFERENCES FOOD(NAME_RU) ;
ALTER TABLE ORDER_DETAILS
  ADD FOREIGN KEY (FOOD_NAME_EN) REFERENCES FOOD(NAME_EN) ;