CREATE TABLE USER (
  ID        INT PRIMARY KEY AUTO_INCREMENT,
  FIRSTNAME VARCHAR(255),
  LASTNAME  VARCHAR(255),
  USERNAME  VARCHAR(255),
  EMAIL     VARCHAR(255),
  PASSWORD  VARCHAR(255),
  ACCESS_ID INT,
  BALANCE   INT
);

ALTER TABLE USER
  ADD FOREIGN KEY (ACCESS_ID) REFERENCES ACCESS (ID);

CREATE TABLE FOOD (
  ID         INT PRIMARY KEY AUTO_INCREMENT,
  TYPE_ID    INT,
  DISCRIPTRU VARCHAR(255),
  DISCRIPTEN VARCHAR(255),
  COMPOSRU   VARCHAR(255),
  COMPOSEN   VARCHAR(255),
  SIZE_ID    INT,
  PRICE      INT,
  IMG        VARCHAR(255)
);
ALTER TABLE FOOD
  ADD FOREIGN KEY (TYPE_ID) REFERENCES TYPE (ID);
ALTER TABLE FOOD
  ADD FOREIGN KEY (SIZE_ID) REFERENCES SIZE (ID);

CREATE TABLE ACCESS (
  ID     INT PRIMARY KEY AUTO_INCREMENT,
  ACCESS VARCHAR(255)
);
CREATE TABLE TYPE (
  ID   INT PRIMARY KEY AUTO_INCREMENT,
  TYPE VARCHAR(255)
);

CREATE TABLE SIZE (
  ID   INT PRIMARY KEY AUTO_INCREMENT,
  SIZE VARCHAR(255)
);

CREATE TABLE CLIENT_ORDER (
  ID      INT PRIMARY KEY AUTO_INCREMENT,
  USER_ID INT,
  SUM     INT,
  ADDRESS VARCHAR(255)
);

CREATE TABLE ORDER_DETAILS (
  ID       INT PRIMARY KEY AUTO_INCREMENT,
  FOOD_ID  INT,
  TYPE_ID  INT,
  SIZE_ID  INT,
  QUANTITY INT

);

ALTER TABLE CLIENT_ORDER
  ADD FOREIGN KEY (USER_ID) REFERENCES USER (ID);
ALTER TABLE ORDER_DETAILS
  ADD FOREIGN KEY (TYPE_ID) REFERENCES TYPE (ID);
ALTER TABLE ORDER_DETAILS
  ADD FOREIGN KEY (SIZE_ID) REFERENCES SIZE (ID);

