CREATE TABLE USER (
  ID        INT PRIMARY KEY AUTO_INCREMENT,
  FIRSTNAME VARCHAR(255),
  LASTNAME  VARCHAR(255),
  USERNAME  VARCHAR(255),
  PASSWORD  VARCHAR(255),
  ACCESS    VARCHAR(6),
  BALANCE   INT
);

CREATE TABLE FOOD (
  ID     INT PRIMARY KEY AUTO_INCREMENT,
  TYPE   VARCHAR(8),
  NAME   VARCHAR(255),
  COMPOS VARCHAR(255),
  SIZE   VARCHAR(6),
  PRICE  INT
);

CREATE TABLE ACCESS (
  ID     INT PRIMARY KEY AUTO_INCREMENT,
  ACCESS VARCHAR(255)
);

CREATE TABLE ORDER_LIST (
  ID      INT PRIMARY KEY AUTO_INCREMENT,
  USER_ID INT,
  SUM     INT,
  FOOD_ID INT
);
ALTER TABLE ORDER_LIST
  ADD FOREIGN KEY (USER_ID) REFERENCES USER (ID);
ALTER TABLE ORDER_LIST
  ADD FOREIGN KEY (FOOD_ID) REFERENCES FOOD (ID);

